### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by bugnounty** [davekolian/Manga-RSS-App#1]
Hi,<br><br>url : https://github.com/davekolian/Manga-RSS-App/blob/c7375af7714ae32ebb204ac79d31d066711ca829/Database-Script-Heroku/database_update.py <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by davekolian** [comment]
Hello,

Thank you for your time, I understood the security issue and have fixed it!

**Comment by bugnounty** [comment]
gald to be help :)
Liked my Bug ? Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
<https://www.paypal.com/paypalme/bugbounty1/150USD>
https://www.buymeacoffee.com/bugbounty
<https://www.buymeacoffee.com/bugbounty>
and help me to continue help small websites.

‫בתאריך יום ב׳, 1 בפבר׳ 2021 ב-0:00 מאת ‪Dave Kol‬‏ <‪
notifications@github.com‬‏>:‬
